### ISSUE TITLE
Broken pipe handling

### ISSUE THREAD

**Issue by IngoMeyer441** [jeffkaufman/icdiff#156]
If `icdiff` output is piped into another application (for example a pager like `less`), it is possible that the second application exits before `icdiff` can write all diff output to `stdout`. In this case, Python raises an IOError like this:
```pytb
Traceback (most recent call last):
  File "/Users/heimbach/Library/Python/2/bin/icdiff", line 11, in <module>
    sys.exit(start())
  File "/Users/heimbach/Library/Python/2.7/lib/python/site-packages/icdiff.py", line 536, in start
    diff(a, b, options=options)
  File "/Users/heimbach/Library/Python/2.7/lib/python/site-packages/icdiff.py", line 562, in diff
    diff_files(options, a, b)
  File "/Users/heimbach/Library/Python/2.7/lib/python/site-packages/icdiff.py", line 638, in diff_files
    sys.stdout.flush()
IOError: [Errno 32] Broken pipe
```
Could you catch the `BrokenPipeError` (Python 3) in https://github.com/jeffkaufman/icdiff/blob/master/icdiff#L726 ?

**Comment by IngoHeimbach** [comment]
Thanks for the quick fix :+1:

**Comment by satta** [comment]
This does not seem to work for me with the installed version of icdiff:
```
[vagrant@debian:~/icdiff] $ icdiff tests/input-{4,5}.txt | head -n 1
tests/input-4.txt                                                                      tests/input-5.txt
Traceback (most recent call last):
  File "/usr/bin/icdiff", line 11, in <module>
    load_entry_point('icdiff==1.9.5', 'console_scripts', 'icdiff')()
  File "/home/vagrant/icdiff/icdiff.py", line 597, in start
    diff(options, *args)
  File "/home/vagrant/icdiff/icdiff.py", line 625, in diff
    raise(e)
  File "/home/vagrant/icdiff/icdiff.py", line 620, in diff
    diff_files(options, a, b)
  File "/home/vagrant/icdiff/icdiff.py", line 754, in diff_files
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
However, when running the icdiff script directly it does work:
```
[vagrant@debian:~/icdiff] $ ./icdiff.py tests/input-{4,5}.txt | head -n 1
tests/input-4.txt                                                                      tests/input-5.txt
```
