### ISSUE TITLE
Handle file not found error

### ISSUE THREAD

**Issue by baskaran-md** [jeffkaufman/icdiff#61]
```
[ec2-user@startrek captain]$ icdiff bootstrap_9.sh bootstrap_10.sh
Traceback (most recent call last):
  File "/usr/local/bin/icdiff", line 603, in <module>
    start()
  File "/usr/local/bin/icdiff", line 511, in start
    diff_files(options, a, b)
  File "/usr/local/bin/icdiff", line 580, in diff_files
    lines_a = read_file(a, options)
  File "/usr/local/bin/icdiff", line 550, in read_file
    with codecs.open(fname, encoding=options.encoding, mode="rb") as inf:
  File "/usr/lib64/python2.7/codecs.py", line 884, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'bootstrap_9.sh'
```

**Comment by baskaran-md** [comment]
Pull Request: https://github.com/jeffkaufman/icdiff/pull/62

**Comment by thinrope** [comment]
That will probably solve the immediate problem, but isn't it better to distinguish between:
* file exists, but is not readable (e.g. permission problem or other ACL) -> error
* file does not exist -> treat as blank (open /dev/null) if `-N, --new-file` switch present (see `man diff`)

**Comment by jeffkaufman** [comment]
Fixed in https://github.com/jeffkaufman/icdiff/pull/101 which is in 1.9.1
